### ISSUE TITLE
[bug] can't run python from 'execute a process' in job main

### ISSUE THREAD

**Issue by lelapenda** [oncase/tarantulla-youtube#2]
Facing issues when running python: 

`Traceback (most recent call last):  
File "/opt/git/tarantulla-youtube/etl/../core/statsMain.py", line 13, in <module>    import statsYoutube as stats  
File "/opt/git/tarantulla-youtube/core/statsYoutube.py", line 8, in <module>    apiKey=os.environ['YTAPIKEY']  
File "/usr/lib/python3.5/os.py", line 725, in __getitem__    raise KeyError(key) from NoneKeyError: 'YTAPIKEY'`

Code is running normally in shell with python3. Problem appears to be related when executing through  PDI interface.

- Environment:

linux OS - ubuntu 16.04
native python3

- Steps to reproduce:

Run main.kjb or _processYoutube.ktr. Error should show up on **Result Output** field from **Execute a Process** step.

**Comment by marpontes** [comment]
Please share information about your environment and steps to reproduce.

**Comment by marpontes** [comment]
What was going on?

**Comment by lelapenda** [comment]
Process wasn't able to find environment variables due to .bashrc outdated. Problem solved with

`source .bashrc`
